### ISSUE TITLE
No kind \"DeleteOptions\" is registered for version \"admissionregistration.k8s.io/v1\" in scheme

### ISSUE THREAD

**Issue by Sibyl1122** [kubevela/workflow#142]
**Describe the bug**

when use the "op.#Delete" for deleting custom resource, there is an error happen: 
`"no kind \"DeleteOptions\" is registered for version \"admissionregistration.k8s.io/v1\" in scheme
           	\"k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go:52\""`

**To Reproduce**

**Expected behavior**

delete target resources successfully and no error be reported

**Screenshots**

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/50979245/221516183-410e2e80-3522-467f-8eaf-13aaef5432ea.png">

**Workflow Version**

<img width="959" alt="image" src="https://user-images.githubusercontent.com/50979245/221516477-23bf395a-ae55-47d9-a688-473587e8e179.png">

**Cluster information**

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/50979245/221516662-f3f39b37-2a5a-421e-9e12-f6935d082e0b.png">

**Additional context**

the same value content for listing resourses  using `op.#List` is correct.

**Comment by Sibyl1122** [comment]
Similar issue： https://github.com/crossplane/crossplane/issues/2284

**Comment by Sibyl1122** [comment]
yaml:
```
apiVersion: core.oam.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: test-delete
  namespace: default
  annotations:
    workflowrun.oam.dev/debug: "true"
spec:
  workflowSpec:
    steps:
      - name: test-delete
        type: test-delete
        properties:
          podName: hdfshttpfs-286nr-0
          namespace: appworkflow

```
cue:
```
import "vela/op"

"test-delete": {
	alias: ""
	annotations: {}
	attributes: {}
	description: ""
	labels: {}
	type: "workflow-step"
}

template: {
	parameter: {
		podName:   string
		namespace: string
	}
	output: {
		del: op.#Delete & {
			value: {
				kind:       "Pod"
				apiVersion: "v1"
				metadata: {
					name:      parameter.podName
					namespace: parameter.namespace
				}
			}
			filter: {
				namespace: parameter.namespace
			}
		}
	}
}
```
![image](https://user-images.githubusercontent.com/50979245/221773850-ba660f0c-9f03-4c64-ad70-805976531abf.png)
When I tested delete function with the Pod, there is no error reported. But the target pod was not  deleted.
