### ISSUE TITLE
Parent step‘s status is “skipped” but its child step was still executed

### ISSUE THREAD

**Issue by Sibyl1122** [kubevela/workflow#145]
**To Reproduce**

yaml 
```
apiVersion: core.oam.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: test-tgt
  namespace: default
  annotations:
    workflowrun.oam.dev/debug: "true"
spec:
  mode:
    steps: StepByStep
    subSteps: StepByStep
  workflowSpec:
    steps:
      - name: mig-group
        type: step-group
        if: input.mock == true
        subSteps:
          - name: read-pod
            type: read-pod
            properties:
              namespace: appworkflow
              podName: hdfsjournalnode-286nr-0
```
cue:
```
import (
	"vela/op"
)

"read-pod": {
	alias: ""
	annotations: {}
	attributes: {}
	description: ""
	labels: {}
	type: "workflow-step"
}

template: {
	parameter: {
		podName:   string
		namespace: string
	}
	read: op.#Read & {
		value: {
			kind:       "Pod"
			apiVersion: "v1"
			metadata: {
				name:      parameter.podName
				namespace: parameter.namespace
			}
		}
	}

}

```

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/50979245/222401816-f714e31c-3a2b-493c-b555-d886b474f346.png)

**Workflow Version**
v0.4.2

**Cluster information**

![image](https://user-images.githubusercontent.com/50979245/222402125-212fb77d-57ca-4bb7-9af7-0e3b8edc22bd.png)
