### ISSUE TITLE
unable to update arrays via parameterKey

### ISSUE THREAD

**Issue by drewwells** [kubevela/workflow#171]
**Describe the bug**
When attempting to update an array in values, it's no longer possible to do so. Instead, it creates a map["0"] entry.

**To Reproduce**
use a parameterKey `myscore[0]`

**Expected behavior**
```
Expected it to produce values [99]
```
Instead it produces
```
{"0":99}
```
**Screenshots**
Actual
<img width="532" alt="image" src="https://github.com/kubevela/workflow/assets/239123/34b69a67-bae1-4f0a-b091-eac09659fc8a">
Expected 
<img width="590" alt="image" src="https://github.com/kubevela/workflow/assets/239123/75866955-4bae-4d39-b793-9ced49e21b2a">

**Additional context**
I tracked down this drift from expected array output to the following PRs

After this PR, an oddity is emitted with `[99,...]` instead of `[99]` https://github.com/kubevela/workflow/pull/86

Arrays can no longer be updated by workflows, instead get treated as maps
https://github.com/kubevela/workflow/pull/112

**Comment by drewwells** [comment]
I tracked down the problem. We have seen several issues in last few release of kubevela, and it may be unrelated to workflow.
Our values are passed from `valuesFrom` in a separate configmap. In that situation, workflow seems to guess types and creates maps instead of arrays. We also can't update annotations without specifying the specific key ie.
```
annotations:
  eks.amazon.com/role: abba
```

If I add this information directly to the application CR values: property, then the behavior of kubevela 0.6.5 workflow 0.3.3 is restored.

**Comment by drewwells** [comment]
Empty arrays get this error as well:

```
invalid cue task for evaluation: runtime error: index out of range
        [0] with length 0
```

We need more flexibility in how to update arrays. I basically have to populate an array in order to use kubevela and this poses problems since this array needs to be null when kubevela isn't operating on it.

**Comment by FogDong** [comment]
Can you provide a workflow yaml to reproduce this?

**Comment by drewwells** [comment]
If you're familiar with cert-manager, it represents solvers in an array:
```
solvers:
- dns01:
   route53:
    region: us-east-1
```

Here's a workflow to attempt to update it
```
    workflow:
      steps:
      - name: read-provider-info
        outputs:
        - name: region
          valueFrom: |
            import "encoding/json"
            json.Unmarshal(output.value.data["data.json"]).region
        - name: hosted_zone_id
          valueFrom: |
            import "encoding/json"
            json.Unmarshal(output.value.data["data.json"]).hosted_zone_id
        properties:
          apiVersion: v1
          kind: ConfigMap
          name: cluster-config-map
          namespace: vela-system
        type: read-object
      - inputs:
        - from: region
          parameterKey: properties.values.solvers[0].dns01.route53.region
        - from: hosted_zone_id
          parameterKey: properties.values.solvers[0].dns01.route53.hostedZoneID
        name: apply
        properties:
          component: cert-manager-issuer
        type: apply-component
```

**Comment by drewwells** [comment]
Annotation workflow example:

```
    workflow:
      steps:
      - name: read-object
        outputs:
        - name: appinfra_grafana_role_arn
          valueFrom: |
            import "encoding/json"
            json.Unmarshal(output.value.data["data.json"]).roles.appinfra_grafana_irsa.arn
        properties:
          apiVersion: v1
          kind: ConfigMap
          name: cluster-config-map
          namespace: vela-system
        type: read-object
      - inputs:
        - from: appinfra_grafana_role_arn
          parameterKey: properties.values.serviceAccount.annotations["eks.amazonaws.com/role-arn"]
        name: apply
        properties:
          component: appinfra-grafana
        type: apply-component
```

I'll get invalid yaml from this workflow until I populate values.yaml with `annotations["eks.amazonaws.com/role-arn"]: ""`
```
annotations:
  "eks.amazonaws.com/role-arn": somevalue
```
