### ISSUE TITLE
Addon-Operation - WFR Status Always Shows Failed

### ISSUE THREAD

**Issue by briankane** [kubevela/workflow#207]
**Describe the bug**
When deploying addons with the addon-operation workflow step, the WorkflowRun always shows status failed despite the addon successfully installing. 

**To Reproduce**
Apply this WorkflowRun:
```
apiVersion: core.oam.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: test-addon-operation
  namespace: default
spec:
  context:
    readConfig: true
    mode:
  workflowSpec:
    steps:
      - name: Enable Prism
        type: addon-operation
        properties:
          addonName: vela-prism
          image: "oamdev/vela-cli:v1.10.3"
```

Check the WFR status which will be in failed status:
```
kubectl get workflowruns.core.oam.dev test-addon-operation
```

However, the addon status will be enabled (or will be):
```
vela addon status vela-prism
```

**Expected behavior**
The WFR should correctly reflect that the addon installed successfully. 

**Screenshots**

**KubeVela Version**
CLI Version: 1.10.3
Core Version: 1.10.3

**Cluster information**
Client Version: v1.31.2

**Additional context**
I'm using an updated image in the addon-operation properties due to the separate issue described in https://github.com/kubevela/kubevela/issues/6801
